### ISSUE TITLE
support microsecond timestamping and display

### ISSUE THREAD

**Issue by bf31415** [aol/moloch#1106]
**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

pcap files timestamp packet arrivals to microsecond resolution.  right now moloch/ES support only millisecond resolution-- which can result in packets which arrive at different microsecond times but the same millisecond time showing out of order on the session page.   would like to maintain the microsecond information so ordering on the session page reflects the actual packet arrival order.

**Comment by awick** [comment]
With ES 7 we can use the new nanosecond support for this (prior versions only had millisecond support)

https://www.elastic.co/guide/en/elasticsearch/reference/7.1/date_nanos.html

But this means we would only enable for folks using ES 7 and/or if Moloch forces ES 7.  Since Moloch 2.0 is just now forcing ES 6 it might be a while.

**Comment by 31453** [comment]
Similar to #1454
