### ISSUE TITLE
moloch-capture immediately+silently quits if ES is not available

### ISSUE THREAD

**Issue by philhagen** [aol/moloch#1138]
When ES is not yet available, and `moloch-capture` is run, it silently and immediately quits.  This is especially problematic when loading pcaps too soon after boot and ES is still warming up.

Would be helpful for at least an error message and return code to be provided so the condition can be handled (user waits, or load process is wrapped in a script that retries the process until successful).

**Comment by awick** [comment]
So if you are using `-q` it shuts off all logging, otherwise I see

`Aug 11 18:20:45 http.c:261 moloch_http_send_sync(): libcurl failure 127.0.0.1:9200/_template/tests_sessions2_template?filter_path=**._meta&include_type_name=true error 'Couldn't connect to server'`

I guess `-q` should show the connect error if its the first one?  Getting tricky what to show and what not to show.

**Comment by philhagen** [comment]
aha - I see.  I think that any error condition that results in desired <thing> not occurring should at least have some indicator on STDERR rather than ending silently.

**Comment by awick** [comment]
Ok, I changed to log any exit msg even in quiet mode.

**Comment by philhagen** [comment]
most excellent - thanks!!

**Comment by awick** [comment]
reopen if not what you wanted.
