### ISSUE TITLE
using capture with -r and named pipe doesn't real-time stream to elastic

### ISSUE THREAD

**Issue by bf31415** [aol/moloch#1169]
To support remotestreaming use cases, we need to ssh into the device and stream the pcap over the ssh session.   this solution entails having the streamed ssh session data to be written (via ssh stdout) to a named pipe.  before starting the ssh session, one starts capture with the "-r <named pipe".

This works in moloch however, the contents read from the named pipe are written to elastic only when the end of file is reached on the pipe-- and this only happens when the ssh feed into the named pipe dies-- which might be hours/days/months later.

there needs to be a slight mod to the startup logic in the following way-- if the -r is specified to capture and there's a single file and this file is of type pipe, the moloch behavior should be as if it's a live session (which is it) rather than a static file with a known file end.

**Comment by awick** [comment]
So if the interface version of the code already works then does just using `interface=/the/pipe` work?

Otherwise need to change reader-libpcap-file.c to use a thread for the pcap reading for the right solution, or allow pcap_dispatch to be called with a configurable number of packets for the quick solution.

**Comment by bf31415** [comment]
Maybe I'm missing something?

ls -las /tmp/pipe
0 prw-r--r-- 1 root root 0 Sep 17 12:45 /tmp/pipe


 grep interface /data/moloch/etc/config.ini
# Semicolon ';' seperated list of interfaces to listen on for traffic
#interface=enp0s10
interface=/tmp/pipe
#interface=enp0s3
# Uses a different interface

 /data/moloch/bin/moloch-capture  -t sll-streaming
Sep 17 14:20:22 main.c:226 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps, use the --host option - moloch-dev
Sep 17 14:20:22 config.c:266 moloch_config_int(): INFO: Reseting tcpSaveTimeout since 5 is less then the min 10
Sep 17 14:20:22 config.c:266 moloch_config_int(): INFO: Reseting logEveryXPackets since 10 is less then the min 1000
Sep 17 14:20:22 reader-libpcap.c:190 reader_libpcap_init(): pcap open live failed! /tmp/pipe: No such device exists (SIOCGIFHWADDR: No such device)

**Comment by awick** [comment]
looks like it doesn't work

**Comment by bf31415** [comment]
yea.  so i got the streaming with -r pipe to work by making the following hacky change.  In a bullpen PR,  I've added logic to see if the ReadFile is a pipe, and now working to refine the code below.  

hack got to work:
    // if (config.pcapReadOffline)
        moloch_readers_set("libpcap-file");
    // else
        moloch_readers_set(NULL);

    // if (!config.pcapReadOffline) {
        moloch_drop_privileges();
        config.copyPcap = 1;
        moloch_mlockall_init();
    // }

More refined logic-- i think this might be whats needed but haven't tested:

    if ((config.pcapReadOffline) && (isPipe == 0)) 
        moloch_readers_set("libpcap-file");
    else
        moloch_readers_set(NULL);

    (!config.pcapReadOffline) {
        moloch_drop_privileges();
        config.copyPcap = 1;
        moloch_mlockall_init();
    }

**Comment by awick** [comment]
Ya I need to see the code, looks like you are calling moloch_readers_set twice which doesn't make sense.

**Comment by awick** [comment]
Went for the easy solution, you can do a `-o offlineDispatchAfter=1` now.  This still requires some packets to be received occasionally for it to work right.

**Comment by bf31415** [comment]
tried this:  

/data/moloch/bin/moloch-capture -o offlineDispatchAfter=1 -r /tmp/pipe --copy -t
sll-streaming-4:24am

and still same behavior-- none of the data is written to elastic until i kill the ssh session. 

other thoughts / ideas?

**Comment by awick** [comment]
So it works locally for me fine, not using ssh but just a local tcpdump

* Just confirming you built yourself, since the build online might not have been updated yet as of when you tested

* It's not going to write it "right away" it has all the same timeouts and everything that moloch has, it just will check if something needs to be done after each packet and not after every 5000 packets.  Like I mentioned above there still needs to be a steady stream of packets so that the event loop runs.

I would suggest running with either a `--debug` and look for the _bulk calls (thats when it writes to ES) or `--tests` and it will just print out the json after each session.

**Comment by bf31415** [comment]
yea, had the wrong build.   its working.  thanks!
