### ISSUE TITLE
S3 Writer Issues

### ISSUE THREAD

**Issue by awick** [aol/moloch#1178]
From Phillip 

>In viewer/viewer.js at around line 5220, you need to add packetLen into the default list of fields to retrieve. This gets the packetLen into the plugin
However, you then run into another problem in the plugin writer-s3/index.js where it is using (at around line 110) async.eachLimit to fetch the packets from S3. Unfortunately, the first invocation (that finds out the filename) has to complete before the second invocation has a chance of working (the params structure is not yet initialized). (edited) 
The cheap workaround is to change the limit to be 1 — but that serializes all the fetches which is not ideal.
I’m not a node expert so I don’t know what the best approach to fixing that second problem is….

Definitely some issues around having more then one file and order of ops.  Might have this issue for disk stuff, or see how we fixed there.  Could prefetch all the files.

**Comment by pjsg** [comment]
I'm certainly going to look at this this week as well. In particular, I'm also going to look at adding support for compressed files. Yes -- sort of tricky, and will take advantage of the fact that JS supports 53 bit integers (and so can encode more than just the packet offset into the packetPos array). Also, some care needed when writing out the compressed files so that (the required level of) seeking can be supported.

**Comment by awick** [comment]
So looking at the code more, processSessionId is supposed to be preloading the file cache, so probably just need to add a new routine that just returns whats in the filecache instead of using a callback.

As far as encoding more the position more information, moloch used to do that for the file num before it started using the negative numbers.  (btw that means you only have 52 bits since we use 53 to mean its a file).

Probably just move this part of the discussion to #728
