### ISSUE TITLE
Moloch v2.0.1 sessions tab loading error (stuck at 'hootin')

### ISSUE THREAD

**Issue by Umor-inbox** [aol/moloch#1260]
**ES: 7.4.1**:
**Moloch version**:v2.0.1
**Ubuntu 18.04.3 LTS"**:
**DB version: 63** (rpm, deb, easybutton, ...)
**Provide logs, stack traces and steps to reproduce**: 
Moloch is unable to load data in the session tab after deployment (looped around "hootin" with an owl image). Re-produce steps:-

a) changes made in config.ini (see attach)
b) started service viewer and capture (logs attached)
3) interface enabled over the virtual machine which was disabled (ifconfig _ens160 up)_
4) span traffic configured over virtual switch

[capture.log](https://github.com/aol/moloch/files/3787992/capture.log)
[viewer.log](https://github.com/aol/moloch/files/3788234/viewer.log)
[config.txt](https://github.com/aol/moloch/files/3788654/config.txt)
![Capture](https://user-images.githubusercontent.com/57136946/67856248-e8dac280-fb35-11e9-8214-dd6785016395.JPG) **(Screenshot taken from Firefox Inspector)**
![Screenshot taken from Chrome](https://user-images.githubusercontent.com/57136946/67856719-fe042100-fb36-11e9-9c2f-6b0e8afcb734.JPG) **(Screenshot taken from Chrome Inspector)**

**Comment by 31453** [comment]
@Umor-inbox Let me know if this fixes your issue. The problem was that the info field was missing children fields (the info column is a list of a few fields). It looks like something else might be wrong, because the info column should always have children fields. Please reopen this issue or open another issue with more details if something is still broken.
