### ISSUE TITLE
Provide more control over request logging from the viewer

### ISSUE THREAD

**Issue by pjsg** [aol/moloch#1375]
For example, I want to be able to suppress the requests to /eshealth.json which (in my environment) happen a lot. Also, the logging currently uses escape sequences to color the output. This just makes automated parsing more complex.

**Comment by awick** [comment]
https://www.npmjs.com/package/morgan

1) I think you could write a skip function that skipped url's in a config var array
2) Could make the format a config var instead of the 

So change the current `app.use(logger(':date :username \x1b[1m:method\x1b[0m \x1b[33m:url\x1b[0m :status :res[content-length] bytes :response-time ms',{stream: _stream}));` to something like

```
internals.somevarname = Config.getArray('somevarname', ';', '');
app.use(logger(Config.get(somevarname), ':date :username \x1b[1m:method\x1b[0m \x1b[33m:url\x1b[0m :status :res[content-length] bytes :response-time ms'), {
stream: _stream,
skip: (req,res) => {return internals.somevarname.includes(req.url))
}));
```


You wanna do a PR? :)

**Comment by pjsg** [comment]
https://github.com/aol/molochweb/pull/14 is the companion documentation PR

**Comment by awick** [comment]
Thanks!
