### ISSUE TITLE
Display TZ and offset of the timestamps are being presented

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#351]
In the display bar between row count and items displayed, show the equivalent of   

echo "TS:"`date +%Z%z`

![ts](https://cloud.githubusercontent.com/assets/125899/6763717/e97c85ea-cf5f-11e4-9728-76e484dea6a2.PNG)

This will remove all doubt for analysts using the interface regarding what TZ they are displaying.

**Comment by awick** [comment]
Maybe they should get therapy instead if they have doubts

Would it be better to place next to the setting in https://localhost:8005/settings instead of on all pages?  Or is this for over the shoulder looking by someone else?

Since the time zone is done in the browser, there currently is no official way to get a name, although there are work around libraries if required.  There is a way to get the offset from GMT, so for example for eastern it would be either GMT-0000 if displaying in GMT time or GMT-0400 if displaying in eastern.

**Comment by WilliamSalusky** [comment]
Placing the TZ reference near the cluster status is good. I only suggested that location since it is physically close to the starttime stoptime columns.

**Comment by awick** [comment]
good enough or you want more? :)

**Comment by WilliamSalusky** [comment]
Unfortunately this one misses the mark. Displaying the actual time is not the request. The intent is to display the TimeZone [not the current time] for which all sessions are being displayed/rendered in.  Ideally this would be on the sessions tab to provide evidence of the timezone for all timestamps presented, and would be available for screenshot capture.

**Comment by awick** [comment]
![image](https://cloud.githubusercontent.com/assets/427321/7006966/800dd022-dc53-11e4-8b77-1ce273508ab6.png)

Ok I tried your suggestion, still deciding if it looks ok

**Comment by awick** [comment]
We now display GMT instead of Z, so it would be possible to have a option to show timestamp everywhere.
