### ISSUE TITLE
Feature request: Purge pcaps based on criterias

### ISSUE THREAD

**Issue by elhoim** [aol/moloch#374]
I would like to be able to purge some of the stored pcaps (not necessarily metadata) based on some criterias. For example, purge all sessions going to ip addresses belonging to AS15169 (google).

The general idea is to increase storage space available for the raw traffic by selectively purging parts of data. The idea is to go beyond what could be filtered out by BPF expressions applied at capture time.

If needed I can clarify and expand this request.

**Comment by awick** [comment]
* It is already possible to scrub pcap and optionally meta data if the Remove Data attribute is set for the operator user.  However this does not free pcap space, although it will free ES space if you remove the meta data.

* You can also record meta data and partial pcap by using the dontSaveTags or dontSaveBPF settings.

* Deleting partial pcap after the fact isn't possible and because of how the pcap is stored isn't practical at this time.
