### ISSUE TITLE
Viewer API startTime/stopTime parameters broken?

### ISSUE THREAD

**Issue by strikaco** [aol/moloch#410]
I'm using a curl request like so:

     curl "localhost:8005/sessions.json?startTime=1437506017"

The idea here is to retrieve all sessions that occurred since a specific time. (The wiki indicates that I don't need to specify date if I use startTime.)

The problem is, I'm not sure what subset of data it's returning. It doesn't match what I'm requesting. I can take it a step further and do:

      curl "localhost:8005/sessions.json?startTime=999999999999999999999999"

This shouldn't return *any* data, but it still returns json objects for some sessions.

I'm using Moloch 0.12.0 on ES 1.6 (I know, not supported). Any thoughts?

**Comment by WilliamSalusky** [comment]
Hi @strikaco,

I need to look at this a bit more, but [case-sensitive] 'startTime' as a query string argname is different from the 'starttime' used as a query keyword used within the "expression" argname. IMHO, both 'startTime' and 'stopTime' are required when using the epoch timestamp query string args, otherwise you'll be rewritten to a default '?date=1'.



https://molo.ch/?startTime=1407293802&stopTime=1438188348

   is not the same as 

https://molo.ch/?date=-3&expression=starttime>-2y

Note that the latter request will be rewritten to specify the relative 'startTime' and 'stopTime'.

I know this doesn't immediately address your question of unexpected json data being returned, but this might help in the meantime.
