### ISSUE TITLE
"Snap To" Timestamp presentation

### ISSUE THREAD

**Issue by WilliamSalusky** [aol/moloch#425]
When SnapTo is selected in the time scope drop down it would be great to have the start time reflect the actual start time of the very first session [and not the end time of the first session]. This allows for easy access to the correct time delta between start and finish of a series of network sessions.

**Comment by awick** [comment]
Yes it can be changed, but just so its clear unless you used the bounded by checked box the query is using the stopTime (or last packet seen in session) anyway.

Bounded by off: (session.stopTime >= BeginningTime) && (session.stopTime <= EndingTime)
Bounded by on: (session.startTime >= BeginningTime) && (session.stopTime <= EndingTime)

So, if we set BeginningTime to startTime instead of StopTime you will get more results.

I find the time rules confusing and probably should be rethought out.  For example if a session starts BEFORE the current BeginningTime AND ends AFTER the current EndingTime it doesn't show up.

Part of the issue is linked sessions keep the same startTime but change stopTime as they are written out.

**Comment by awick** [comment]
0.17 newUI now has multiple time options, open new issue if you want something else
