### ISSUE TITLE
Elasticsearch 2.3.x?

### ISSUE THREAD

**Issue by jhart-r7** [aol/moloch#563]
The documentation says that 2.4 is required in one place, but in other it seems to imply at least 2.1.x.  

Is 2.3.x supported?  I ask because AWS provides managed ES clusters which simplifies things greatly but they are currently 2.3.2 and 1.5 (IIRC).

**Comment by awick** [comment]
It depends on the Moloch version, in general we continue to require newer and newer versions of ES as we go.

0.13.0 - 0.16.1 should support ES 2.3
0.17.0-GIT is currently requiring ES 2.4, but I may change that back to ES 2.3 (it was 2.1 in the code previously)

The issue is that ES 5 requires upgrading from ES 2.[34] currently, so might as well get folks on to ES 2.4 for whenever we are ready to support ES 5.  ES 5 is NOT supported yet.

**Comment by jhart-r7** [comment]
👍 thanks.  There are additional gotchas with using the AWS ES instance, but as of yet I don't think they are blockers for moloch.
