### ISSUE TITLE
Upgrading to 0.17.X elasticsearch problems. (Solved)

### ISSUE THREAD

**Issue by problematiq** [aol/moloch#616]
Just wanted to note I figured out why I was having problems getting Elasticsearch to listen on port 9200 after updating Moloch. Problem was the /data/moloch/data/Moloch directory and sub-directory's need to be owned by nobody and nogroup. `chown -R nobody:nogroup /data/moloch/data/Moloch` Mine was owned by the user and group was the user.

**Comment by awick** [comment]
The configure script has
```chown nobody /data/$MOLOCH_NAME/data /data/$MOLOCH_NAME/etc/scripts``` so they should already be owned by nobody before elasticsearch even starts.

**Comment by problematiq** [comment]
It is changing ownership of /data but not it's sub-directory's

**Comment by awick** [comment]
There should be no sub directories when it is installed.  Maybe you ran elasticsearch as root first?  /data/moloch/data is empty and is create in Configure right above the chown.

**Comment by problematiq** [comment]
This is an upgrade of an existing Moloch install (ver 0.16.1). so there is already an existing /data/moloch/data as well as sub-directory's

**Comment by awick** [comment]
Who was it owned by?  0.16.1 has the same mkdir and chown, so in order to write in that dir you had to be nobody or root.  You said "Mine was owned by the user and group was the user" which I don't follow.

**Comment by problematiq** [comment]
It depends on the box. ones that I upgraded from 0.13.X are sysadmin:sysadmin and the ones that were 0.16.X are daemon:root

**Comment by awick** [comment]
> It depends on the box. ones that I upgraded from 0.13.X are sysadmin:sysadmin and the ones that were 0.16.X are daemon:root

1) You don't even need to run Configure when upgrading usually 
2) You definitely should say no to the ES part (I guess it should tell you that.)
3) 0.16 was never daemon:root for ES, so not sure how the ES directory got that way.  confusing.

> I realize running ES on the capture server is not ideal, but these servers are remote and as the guys from ES say "ES database+remote location=bad" these are beefy boxes though: (128G ram, 32TB storage, X4 Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz)

I don't understand what you mean here.  The ES guys say its bad to have multiple nodes in 1 cluster in different locations, NOT that the client and server have to be in the same location.  We run remote captures with locale ES with no issue.  But if it works for you thats great.  The ES that Configure sets up is really just for a demo, just say no from now on and those issues will go away.

Anyway, I'm closing this since I don't really think there is a bug, or I guess I don't understand what it is.
