### ISSUE TITLE
How to configure Elasticsearch auth?

### ISSUE THREAD

**Issue by wcc526** [aol/moloch#679]
**Elasticsearch version**:
2.4.4

**Moloch version**:
latest

**OS name and version**:

CentOS 7

How to configure Elasticsearch with Auth?

**Comment by awick** [comment]
What type of auth?  Currently moloch doesn't support any ES auth.

**Comment by wcc526** [comment]
Xpack https://www.elastic.co/guide/en/x-pack/current/security-getting-started.html

**Comment by awick** [comment]
So you want basic auth support?

**Comment by wcc526** [comment]
Yes,ACL is very important

**Comment by awick** [comment]
ACL is on the ES side, moloch doesn't nor will never do anything for that.

**Comment by wcc526** [comment]
Could you add a option for http auth for ES?ACL is used for ES cluster in production.

**Comment by awick** [comment]
This is why I was trying understand what your request was.

**Comment by awick** [comment]
Fixed in 2abdfa4669d98f60443ac570938735451cf6a5bd  Just set the user/pass in the url

**Comment by jvernon214** [comment]
Hi I'm attempting to use an Elastic Cloud instance to store the data captured by Moloch.  I have X-Pack security installed on this cluster and https.  I'm attempting to pass use: https://username:password@cluser_ip:9243 but I keep getting errors that my cluster is unreachable.  I have confirmed that my cluster is actually up and running by CURLing the url. Is xpack security currently supported in Moloch?

**Comment by awick** [comment]
Please always provide versions number in bug reports, in this case for both moloch and es.  Your future bug report recipients will appreciate it.

Moloch just uses libcurl, so the exact same url should work with both.  Double check you are using the exact same url.

**Comment by jvernon214** [comment]
Sorry about that @awick.

Moloch Version: https://files.molo.ch/builds/centos-6/moloch-1.1.1-1.x86_64.rpm
Elasticsearch: 6.2.4

**Comment by awick** [comment]
I tried 6.2.4 with xpack both locally and with found.io and it worked.  The found.io version required a newer version to perl to get the right CA certs.

You can add `--debug --debug --debug` to your capture command and look at the logs for the elasticsearch variable to double check it matches what you are using with curl and to see the output.

**Comment by jvernon214** [comment]
Do you happen to know which version of Perl that was?

**Comment by awick** [comment]
Using MacPorts I went to v5.26.2 and the latest LWP

**Comment by jvernon214** [comment]
Alright great.  Updating perl on my machine now.

**Comment by Osipion** [comment]
@awick - First, thanks for your work on Arkime. It's a great tool and I'm grateful to everyone who helped build it. 

On the issue of ES auth it'd be great if instead of/as well as basic auth the use of an API key was supported. Basic auth, particularly where the username and password are embedded in the URL has multiple well-known drawbacks, and in this case the password is logged in the clear in log files:  e.g. /data/moloch/logs/capture.log. It'd be awesome if we could use API keys to authenticate with ES instances in Elastic Cloud instead and, I'd hope (but am absolutely no expert on this codebase) that it wouldn't be too difficult to achieve?

Thanks.
