### ISSUE TITLE
Packets arriving out of order

### ISSUE THREAD

**Issue by b3n7s** [aol/moloch#693]
I am currently experiencing a problem with the capture component of Moloch.

I have a lot of "acked-unseen-segment-src" and "acked-unseen-segment-dst" in my tags (1 out of 10 sessions have this tag).

When I investigate why, I see that actually all packets are there, both they are not recorded in the correct order. If I sort the packets on timestamp, then everything is okay!

I did a capture with tcpdump on the same machine and of the same session as a Moloch capture. Both captures (the one captured by Moloch and the one capture by tcpdump) are in attachement.

Both contain 67 packets.

Does anyone have an idea. It seems the same problem as this one: https://github.com/aol/moloch/issues/465

Some context:

OS: Ubuntu 14.04.5 LTS
Version: moloch-0.18.2

$ ethtool -i em3
driver: tg3
version: 3.137
firmware-version: 5719-v1.38 NCSI v1.2.41.0
bus-info: 0000:03:00.2
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

$ ethtool -g em3
Ring parameters for em3:
Pre-set maximums:
RX:		2047
RX Mini:	0
RX Jumbo:	0
TX:		511
Current hardware settings:
RX:		2047
RX Mini:	0
RX Jumbo:	0
TX:		511

$ ethtool -k em3
Features for em3:
rx-checksumming: off
tx-checksumming: off
	tx-checksum-ipv4: off
	tx-checksum-ip-generic: off [fixed]
	tx-checksum-ipv6: off
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: off [fixed]
scatter-gather: off
	tx-scatter-gather: off
	tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: off
	tx-tcp-segmentation: off
	tx-tcp-ecn-segmentation: off
	tx-tcp6-segmentation: off
udp-fragmentation-offload: off [fixed]
generic-segmentation-offload: off
generic-receive-offload: off
large-receive-offload: off [fixed]
rx-vlan-offload: on [fixed]
tx-vlan-offload: on [fixed]
ntuple-filters: off [fixed]
receive-hashing: off [fixed]
highdma: on
rx-vlan-filter: off [fixed]
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-ipip-segmentation: off [fixed]
tx-sit-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
tx-mpls-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off [fixed]
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
busy-poll: off [fixed]

**Comment by awick** [comment]
Looking at both the moloch and the tcpdump pcaps from the mailing list, they both have incorrectly timestamped packets.  Have you tried the tpacketv3 reader and see if that fixes the issue?  This may require that you turn off rx-vlan-offload which isn't possible on your card :(  does this happen with sessions without vlan packets?

Unfortunately in moloch there is no easy fix since we assume we will receive the packets in timestamp order, which isn't happening in this case.

However, this doesn't really matter unless you are trying to use moloch to diagnose network issues directly.  Moloch will still reassemble the tcp session correctly, but it will look like it sent them out of order instead of the driver/kernel/.. mixing up the order.
