### ISSUE TITLE
Any plans for PostgreSQL?

### ISSUE THREAD

**Issue by ffries** [aol/moloch#736]
Hello,

Moloch seems fantastic. Without digging in the SPEC I am not very enclined in using Elastic Search (ES). ES seems like chaos. I am quite surprised to see an infratructure where indexing is done on third party servers ...

I would expect PostgreSQL to be able to index pcap files ? But really NO:
I searched the Internet during hours and did not find anything linking pcap/libpcap to a dabase schema.

Could you explain shortly why you used ES and not PostgreSQL (or any other database) in a first place?

Kind regards,
Kellogs

**Comment by awick** [comment]
> Moloch seems fantastic. Without digging in the SPEC I am not very enclined in using Elastic Search (ES). ES seems like chaos. I am quite surprised to see an infratructure where indexing is done on third party servers ...

Not sure what you mean, we run elasticsearch on our own servers.  Are you confusing an amazon service with ES?


> Could you explain shortly why you used ES and not PostgreSQL (or any other database) in a first place?

Sure just the basic speed, scale, and feature set reasons. :)

Haven't looked in a while but most relational DBs have poor free text search, poor multi level aggregations (finding unique values), poor multi host support (unless you are an expert), poor support when the whole database doesn't fit in memory, etc etc.  We did try mongo when we started and it had issues too.  Five years later we could look at other databases, but many security orgs are already using ES because of ELK.
