### ISSUE TITLE
Retains legacy file paths, manual pcap import/capture

### ISSUE THREAD

**Issue by skBeyond** [aol/moloch#807]
**Elastic 5.5.3**:

**Moloch 0.50.0**:

** RHEL 7.4**:

**RPM install:** (viewer node issue)

When performing moloch capture I noticed that the legacy file paths are retained on pcap sessions even though the pcap files are re-ingested under a different name and location. 

To confirm that elastic search was not retaining older indexes I performed a ./db.pl WIPE and INIT.

**Comment by awick** [comment]
What command line are you using?  If you are using --copy that will make a copy and use new file names.  If you don't use --copy it will just use the copy on disk and behave like you see.

**Comment by skBeyond** [comment]
Yep, was not using the --copy extension, using below:

/data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini -r /tmp/testdata/maccdc2012_00000.pcap 

But still a issue wouldn't you think? Maybe a change in the viewer if nothing else

**Comment by awick** [comment]
@skBeyond I don't understand the bug here, it shows the path it was loaded from on purpose.  You can also search for that filename.  Like @WilliamSalusky mentioned, if you don't say --copy then viewer will expect the file to still be there if you want to view the actual pcap.  So in your example of you open up a session from the file `/tmp/testdata/maccdc2012_00000.pcap` it is going to expect that file to still exist since you didn't use `--copy`.

**Comment by skBeyond** [comment]
Ah ok, so in my scenario I failed to mention that I had removed the original pcap file, and wanted to eliminate any ties back to the original path.  To do this I ran both INIT and WIPE on the elastic search cluster.  I simply re-ingested from a different location, however the viewer still retained the old file path, is there a to completely flush out all reference of past ingested data and have an old file treated as a new one?

**Comment by awick** [comment]
init and wipe are the same thing, other then wipe doesn't clear the users database.  Running either will erase all references to all files and sessions.  Running both isn't required.  If you left viewer running while doing wipe/init then it may have cache data for a little bit of time.  You should always restart viewer with wipe/init like the script warnings you.  Although since all the sessions would have been cleared this doesn't make sense.

If you want to move a file location in the db there is a `db.pl mv` command.  But if you are renaming from one file that doesn't exist to another file that doesn't exist, not sure why other then what it shows in viewer.

**Comment by skBeyond** [comment]
yeah guess a little over zealous using INIT and WIPE lol, I had the viewer up and it makes sense that it would cache that location and likely cause the issues I was having.  I did verify in the viewer that all sessions were gone, yet upon re-ingest that data the older file location was still visible, I will try replicating the issue will full wipe and restart of the viewer services.  Thanks again
