### ISSUE TITLE
API enhancements

### ISSUE THREAD

**Issue by jolan78** [aol/moloch#875]
**Elasticsearch version**: 5.6.9

**Moloch version**: 1.1.1

**OS name and version**: Ubuntu 18.04

**How was Moloch built/installed:** deb

- It would be helpfull to quickly query the timestamp of the last session in the database. stats.json would be a good candidate to provide this information (is it usable by API clients ? if so maybe it could be documented in the wiki). Currently I have to use unique.txt for this but it is not efficient.
ideally, the timestamp before witch moloch is guaranteed to have every session in database would be very useful to me but I doubt it would be implementable as it would require moloch-capture to communicate on unfinished sessions it is recording.

- addTag could return the number of session it tagged.

**Comment by awick** [comment]
In the future please open multiple issues if the ideas are for totally different end points.

Is there a reason that the max should be in viewer instead of just going against ES directly?  

Using either the max or stats aggregation will return the result

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-max-aggregation.html

```
curl -X POST "localhost:9200/sessions2*/_search?size=0&pretty" -H 'Content-Type: application/json' -d '{
    "aggs" : {
        "lastPacket" : { "max" : { "field" : "lastPacket" } },
        "timestamp" : { "max" : { "field" : "timestamp" } }
    }}'
```

You can calculate the time for which all sessions should be in the db, it should be something like currentTime - MAX(of all the session timeouts) - dbFlushTimeout - elasticsearch refresh time - max round trip time  = its about 11 minutes if using the default if I remember right.

**Comment by jolan78** [comment]
sorry for the multiple issues.

Using aggregations is not possible for me, as I need to frequently know what moloch have in the db, and this would load my server too much. Also, being independent of the backend seemed to be a good idea.
I can work around this but I thought it would be usefull to other tagging solutions.

**Comment by awick** [comment]
If I implemented in viewer it would just call this endpoint, I guess I'm missing your idea for a solution.  Aggregations are not nearly as expensive anymore, especially what looking at min/max for fields they are pre calculated per index.

Come over to slack for an easier discussion

**Comment by awick** [comment]
I think we solved this in slack, let me know if not
