### ISSUE TITLE
Ungraceful Capture Exit

### ISSUE THREAD

**Issue by aminlatifi** [aol/moloch#877]
I use `systemctl stop molochcapture.service` to stop Moloch capture service. Unfortunately,  some packets , not dumped yet, are lost by stopping capture service by this way. These packets are not available in dumped pcap files (in /data/moloch/raw). Also, I feel some SIP records are not available.
I solved this problem by sending SIGINT signal to capture process manually (`/data/moloch/bin/moloch-capture -c /data/moloch/etc/config.ini`).  Maybe safer exit should be supported when stopping service by `systemctl`.

**Moloch version**:1.1.0

**OS name and version**:Debian 9

**How was Moloch built/installed:** easybutton

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
Some packets are always going to be lost on restart.  As soon as you hit enter, new packet capture must stop otherwise we will never restart.  So then the question is would it be better to drop whats in the queue now so you can start processing new packets as fast as possible (SIGTERM), or would it be better to flush what you have delaying new packet capture so the current stuff can finish (SIGINT).  

I think the default of SIGTERM is better since I can always delay hitting enter.

with systemd you can change `KillSignal=SIGINT` to get the other behaviour, see `man systemd.kill`
